### ISSUE TITLE
fix build

### ISSUE THREAD

**Issue by tubbynl** [Devoxx4Kids-NPO/littil-documentation#26]
1 error and 1 warning

The following actions uses node12 which  is deprecated and will be forced to run on node16: actions/checkout@v2. 
For more info:  https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

https://github.com/Devoxx4Kids-NPO/littil-documentation/actions/runs/6290022981/job/17077089602  in step Generate en publish documentation

           
```
Run docker run -v ${PWD}:/docs --entrypoint "/bin/sh" local -c "/usr/bin/git config --global --add safe.directory /docs && mkdocs gh-deploy --force"
  docker run -v ${PWD}:/docs --entrypoint "/bin/sh" local -c "/usr/bin/git config --global --add safe.directory /docs && mkdocs gh-deploy --force"
  shell: /usr/bin/bash -e {0}
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /docs/site
INFO    -  DeprecationWarning: A plugin has set File.page to an instance of Page and it got overwritten. The behavior of this will change in MkDocs 1.6.
  File "/usr/local/lib/python3.11/site-packages/mkdocs/structure/nav.py", line 192, in <listcomp>
    else _data_to_navigation(item, files, config)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/structure/nav.py", line 209, in _data_to_navigation
    warnings.warn(

ERROR   -  Error reading page 'index.md': 
root dir: /docs/docs/diagrams, src dir: /docs/docs/diagrams/src
Converting /docs/docs/diagrams/src/registration.puml
Converting /docs/docs/diagrams/src/fetch-address-coordinates.puml
Converting /docs/docs/diagrams/src/example.puml
Converting /docs/docs/diagrams/src/user-model-mapping.puml
Converting /docs/docs/diagrams/src/registration-process-sequence-diagram.puml
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/__main__.py", line 313, in gh_deploy_command
    build.build(cfg, dirty=not clean)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 322, in build
    _populate_page(file.page, config, files, dirty)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 171, in _populate_page
    page.markdown = config.plugins.on_page_markdown(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/plugins.py", line 575, in on_page_markdown
    return self.run_event('page_markdown', markdown, page=page, config=config, files=files)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/plugins.py", line 507, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs_git_snippet/plugin.py", line 48, in on_page_markdown
    return md_template.render(gitsnippet=self.gitsnippet)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 45, in top-level template code
  File "/usr/local/lib/python3.11/site-packages/mkdocs_git_snippet/plugin.py", line 41, in gitsnippet
    return self._git_snippet(repository, file, ref, section)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs_git_snippet/plugin.py", line 23, in _git_snippet
    g = Github(auth=Auth.Token(os.getenv("GITHUB_TOKEN")))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/github/Auth.py", line 107, in __init__
    assert isinstance(token, str)
AssertionError
Error: Process completed with exit code 1.
```

**Comment by MarcelWildenburg** [comment]
update main branch to actions/checkout@v4
Waiting for next commit with changes in docs to validate if this is solved.

**Comment by MarcelWildenburg** [comment]
issue is solved.
